/* ═══════════════════════════════════════════════════════════════════════
   Cantos da Mata — otimizador de imagens
   Lê as fotos originais em ../Pousada/FotosJu/CANTOS DA MATA/<CHALÉ>/
   e gera webp web (1600px e 800px) em ../assets/images/<slug>/ + manifesto.

   Uso:  cd tools && npm install sharp && node optimize-images.js
   ═══════════════════════════════════════════════════════════════════════ */
const sharp = require('sharp');
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SRC = path.join(ROOT, 'Pousada', 'FotosJu', 'CANTOS DA MATA');
const OUT = path.join(ROOT, 'assets', 'images');
const JS_OUT = path.join(ROOT, 'assets', 'js', 'gallery-data.js');

const SLUGS = [
  { match: /abrigo/i, slug: 'abrigo', label: 'Abrigo na Mata' },
  { match: /caracol/i, slug: 'caracol', label: 'Caracol' },
  { match: /casa de pedra/i, slug: 'casa-de-pedra', label: 'Casa de Pedra' },
  { match: /casinha/i, slug: 'casinha', label: 'Casinha na Mata' },
  { match: /areas|caf/i, slug: 'areas', label: 'Áreas & Café' },
];

const idx = (f) => { const m = f.match(/-(\d+)\.jpe?g$/i); return m ? parseInt(m[1], 10) : 1; };
const coverFirst = (files) => files.filter(f => /\.jpe?g$/i.test(f)).sort((a, b) => idx(a) - idx(b));

async function main() {
  if (!fs.existsSync(SRC)) { console.error('Pasta de origem não encontrada:', SRC); process.exit(1); }
  const manifest = {};
  let totalOut = 0;
  for (const d of fs.readdirSync(SRC, { withFileTypes: true }).filter(e => e.isDirectory())) {
    const map = SLUGS.find(s => s.match.test(d.name));
    if (!map) { console.log('IGNORADO (sem slug):', d.name); continue; }
    const srcDir = path.join(SRC, d.name);
    const outDir = path.join(OUT, map.slug);
    fs.mkdirSync(outDir, { recursive: true });
    const files = coverFirst(fs.readdirSync(srcDir));
    manifest[map.slug] = { label: map.label, count: files.length, images: [] };
    let n = 0;
    for (const f of files) {
      const id = String(++n).padStart(2, '0');
      const base = `${map.slug}-${id}`;
      const big = path.join(outDir, `${base}-1600.webp`);
      const small = path.join(outDir, `${base}-800.webp`);
      await sharp(path.join(srcDir, f)).rotate().resize({ width: 1600, height: 1600, fit: 'inside', withoutEnlargement: true }).webp({ quality: 80 }).toFile(big);
      await sharp(path.join(srcDir, f)).rotate().resize({ width: 800, height: 800, fit: 'inside', withoutEnlargement: true }).webp({ quality: 78 }).toFile(small);
      totalOut += fs.statSync(big).size + fs.statSync(small).size;
      manifest[map.slug].images.push({ big: `assets/images/${map.slug}/${base}-1600.webp`, small: `assets/images/${map.slug}/${base}-800.webp` });
    }
    console.log(`OK ${map.slug}: ${files.length} imagens`);
  }
  fs.writeFileSync(JS_OUT,
    '// AUTO-GENERATED by tools/optimize-images.js — manifesto de imagens (file://-safe, sem fetch)\n'
    + 'window.CDM_GALLERY = ' + JSON.stringify(manifest, null, 2) + ';\n', 'utf8');
  console.log(`Manifesto -> ${JS_OUT}`);
  console.log(`Total otimizado: ${(totalOut / 1024 / 1024).toFixed(1)} MB`);
}
main().catch(e => { console.error(e); process.exit(1); });
